"""Shared configuration and audit helpers for the GTRI data pipeline."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "output"
DOCS_DIR = PROJECT_ROOT / "docs"

YEARS = (2017, 2022)

# UN M49 reporter codes, ISO3 identifiers, and Correlates of War state codes.
COUNTRIES = (
    {"country": "Malaysia", "iso3": "MYS", "comtrade": 458, "cow": 820},
    {"country": "Vietnam", "iso3": "VNM", "comtrade": 704, "cow": 816},
    {"country": "Singapore", "iso3": "SGP", "comtrade": 702, "cow": 830},
    {"country": "Thailand", "iso3": "THA", "comtrade": 764, "cow": 800},
    # UN Comtrade uses reporter 699 for post-1974 India; 356 is the expired
    # historical entity "India (...1974)" even though both expose ISO3 IND.
    {"country": "India", "iso3": "IND", "comtrade": 699, "cow": 750},
    {"country": "Indonesia", "iso3": "IDN", "comtrade": 360, "cow": 850},
    {"country": "Philippines", "iso3": "PHL", "comtrade": 608, "cow": 840},
    {"country": "Japan", "iso3": "JPN", "comtrade": 392, "cow": 740},
    {"country": "South Korea", "iso3": "KOR", "comtrade": 410, "cow": 732},
    {"country": "Mexico", "iso3": "MEX", "comtrade": 484, "cow": 70},
    {"country": "Germany", "iso3": "DEU", "comtrade": 276, "cow": 255},
    {"country": "Netherlands", "iso3": "NLD", "comtrade": 528, "cow": 210},
)


def ensure_directories() -> None:
    for path in (
        RAW_DIR / "comtrade",
        RAW_DIR / "unga",
        RAW_DIR / "atop",
        RAW_DIR / "tiva",
        RAW_DIR / "bis",
        RAW_DIR / "p2",
        RAW_DIR / "fdi",
        PROCESSED_DIR,
        OUTPUT_DIR,
        DOCS_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def append_progress(module: str, status: str, details: list[str]) -> None:
    """Append a timestamped, human-readable audit entry."""
    ensure_directories()
    log = DOCS_DIR / "progress_log.md"
    if not log.exists():
        log.write_text(
            "# GTRI data-pipeline progress log\n\n"
            "This file is generated by the pipeline. Missing data and failures "
            "are recorded explicitly; no values are imputed.\n",
            encoding="utf-8",
        )
    with log.open("a", encoding="utf-8") as handle:
        handle.write(f"\n## {utc_now()} — {module}: {status}\n\n")
        for item in details:
            handle.write(f"- {item}\n")
